TOTAL_WIDTH = 80
TOTAL_BORDER =  "*" * TOTAL_WIDTH
TOTAL_EMPTY_ROW = "*" + " " * (TOTAL_WIDTH - 2) + "*"

BORDER_WIDTH = 60
BORDER = '*' * BORDER_WIDTH
HALF_WIDTH = int((TOTAL_WIDTH - BORDER_WIDTH) / 2)
EMPTY_ROW = " " * (HALF_WIDTH) + "*" + " " * (BORDER_WIDTH - 2) + "*"

V_PAD = 1